# Generated by Django 3.2.5 on 2021-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nama_anggota2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prodi_anggota2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
