# Generated by Django 3.2.2 on 2021-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='file_pdf',
            field=models.FileField(upload_to='prototype/file_lomba'),
        ),
    ]
