# Generated by Django 3.2.5 on 2021-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='nama_anggota3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='nama_anggota4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='prodi_anggota3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='prodi_anggota4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
